### ISSUE TITLE
Unknown error for all mutations

### ISSUE THREAD

**Issue by paireks** [Testura/Testura.Mutation#60]
Hey guys,  I'm excited, this tool looks great, but I can't figure out one thing, maybe you can help me with that. Mutations look good, but everytime I try to run all those mutations, they all have "unknown error while running". I map this all properly (I think), so it's probably not the issue.
I've created simple example that have the same problems:
[SampleProject.zip](https://github.com/Testura/Testura.Mutation/files/4459151/SampleProject.zip)

Used test framework: xunit
If you need more information please let me know.

**Comment by MilleBo** [comment]
Hey! 

I actually had a bug with xunit. But it should be fixed new and I have upload a new version (1.10.1 if you are running visual studio extension and 1.8.2 if you use the console). 

Please try it out and see if it work better.

**Comment by paireks** [comment]
Still the same problem with 1.10.1. in these projects, mutations are being created well, but they all have unknown error.

**Comment by MilleBo** [comment]
hmm that's weird. I just downloaded 1.10.1 and tried it on your project and all my mutations turn green with the fix.

Can you see anything in the mutation output window?

**Comment by paireks** [comment]
![Testura](https://user-images.githubusercontent.com/47977819/78981568-76c4cb80-7b20-11ea-96a9-ae96ee51f589.png)

**Comment by MilleBo** [comment]
![log](https://user-images.githubusercontent.com/7266147/78982711-ffdd0200-7b22-11ea-8ac5-3a5ab60030a7.PNG)

Can you post the log from here? I usually have pretty bad logging for these unknown errors but maybe we see something.

**Comment by MilleBo** [comment]
I see that you run with a different language so maybe it have something to do with that. Because I have this check after running the tests: 

`var success = !string.IsNullOrEmpty(resultFile) && (string.IsNullOrEmpty(error) || error.Contains("Test Run Failed"));`

So maybe your console output will be something else than "Test Run Failed" :/

**Comment by paireks** [comment]
2020-04-10 12:02:50,029[INFO]: # Handling OpenProjectCommand # 
2020-04-10 12:02:50,031[INFO]: Opening project at C:\Users\User\source\repos\ClassLibrary1\ClassLibrary1.sln 
2020-04-10 12:02:50,146[INFO]: Loading mutators.. 
2020-04-10 12:02:50,153[INFO]: ..found mutators in config. 
2020-04-10 12:02:50,155[INFO]: Adding 'ConditionalBoundary' mutator 
2020-04-10 12:02:50,156[INFO]: Adding 'NegateCondtional' mutator 
2020-04-10 12:02:50,157[INFO]: Adding 'Math' mutator 
2020-04-10 12:02:50,159[INFO]: Adding 'NegateTypeCompability' mutator 
2020-04-10 12:02:50,160[INFO]: Adding 'Increment' mutator 
2020-04-10 12:02:50,161[INFO]: Adding 'ReturnValue' mutator 
2020-04-10 12:02:50,163[INFO]: Adding 'MethodCall' mutator 
2020-04-10 12:02:50,164[INFO]: Setting up mutation projects. 
2020-04-10 12:02:50,165[INFO]: Grabbing output info for ClassLibrary1. 
2020-04-10 12:02:50,166[INFO]: Setting up test projects. 
2020-04-10 12:02:50,168[INFO]: Found the test project XUnitTestProject1. Grabbing output info. 
2020-04-10 12:02:50,169[INFO]: Wanted build configuration is "Debug". Setting test project output to "C:\Users\User\source\repos\XUnitTestProject1\bin\Debug\netcoreapp3.1\XUnitTestProject1.dll" 
2020-04-10 12:02:50,170[INFO]: Test runner: DotNet 
2020-04-10 12:02:50,171[INFO]: Creating baseline and verifying solution/tests.. 
2020-04-10 12:02:50,173[INFO]: Starting to compile ClassLibrary1.. 
2020-04-10 12:02:50,177[INFO]: .. compiled successfully. 
2020-04-10 12:02:50,178[INFO]: Starting to run tests in XUnitTestProject1.dll 
2020-04-10 12:02:53,068[INFO]: ..done (3 tests passed). 
2020-04-10 12:02:53,069[INFO]: +----- Test result -----+ 
2020-04-10 12:02:53,071[INFO]: XUnitTestProject1                        00:00:01.5323804 
2020-04-10 12:02:53,072[INFO]: +----- ------------ -----+ 
2020-04-10 12:02:53,073[INFO]: Baseline completed. 
2020-04-10 12:02:53,101[INFO]: Opening project finished. 
2020-04-10 12:02:53,102[INFO]: # Handled OpenProjectCommand # 
2020-04-10 12:02:53,103[INFO]: # Handling CreateMutationsCommand # 
2020-04-10 12:02:53,105[INFO]: Starting to analyze test.. 
2020-04-10 12:02:53,106[INFO]: Starting to create mutations for ClassLibrary1.. 
2020-04-10 12:02:53,107[INFO]: Creating mutation for Class1.cs.. 
2020-04-10 12:02:53,109[INFO]: Creating mutation for .NETFramework,Version=v4.5.AssemblyAttributes.cs.. 
2020-04-10 12:02:53,110[INFO]: Creating mutation for AssemblyInfo.cs.. 
2020-04-10 12:02:53,112[INFO]: # Handled CreateMutationsCommand # 
2020-04-10 12:02:55,491[INFO]: # Handling ExecuteMutationsCommand # 
2020-04-10 12:02:55,493[INFO]: Total number of mutations generated: 5 
2020-04-10 12:02:55,494[INFO]: Running mutation: "Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:20))" 
2020-04-10 12:02:55,494[INFO]: Running mutation: "Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:27))" 
2020-04-10 12:02:55,494[INFO]: Running mutation: "Proj: ClassLibrary1, File: Class1.cs(Hello(M) - @(22:13))" 
2020-04-10 12:02:55,550[INFO]: Compiling mutation Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:27)) to c:\users\user\appdata\local\microsoft\visualstudio\16.0_ffb9c984\extensions\yb2lymwz.gkl\TestRun\anke5yys.21a\ClassLibrary1.dll 
2020-04-10 12:02:55,551[INFO]: Compiling mutation Proj: ClassLibrary1, File: Class1.cs(Hello(M) - @(22:13)) to c:\users\user\appdata\local\microsoft\visualstudio\16.0_ffb9c984\extensions\yb2lymwz.gkl\TestRun\i4ovembp.fy0\ClassLibrary1.dll 
2020-04-10 12:02:55,550[INFO]: Compiling mutation Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:20)) to c:\users\user\appdata\local\microsoft\visualstudio\16.0_ffb9c984\extensions\yb2lymwz.gkl\TestRun\bwttnxza.qub\ClassLibrary1.dll 
2020-04-10 12:02:55,564[INFO]: Compiled Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:27)) successfully. 
2020-04-10 12:02:55,564[INFO]: Compiled Proj: ClassLibrary1, File: Class1.cs(Hello(M) - @(22:13)) successfully. 
2020-04-10 12:02:55,567[INFO]: Compiled Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:20)) successfully. 
2020-04-10 12:02:55,569[INFO]: Starting to run tests in XUnitTestProject1.dll 
2020-04-10 12:02:55,570[INFO]: Starting to run tests in XUnitTestProject1.dll 
2020-04-10 12:02:55,578[INFO]: Starting to run tests in XUnitTestProject1.dll 
2020-04-10 12:02:58,275[WARN]: Unexpected exception when running Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:27)) 
2020-04-10 12:02:58,276[WARN]: Unexpected exception when running Proj: ClassLibrary1, File: Class1.cs(Calculate(M) - @(16:20)) 
2020-04-10 12:02:58,276[INFO]: Will put it in the unknown category. 
2020-04-10 12:02:58,277[INFO]: Will put it in the unknown category. 
2020-04-10 12:02:58,278[INFO]: Current progress: { Survived: 0, Killed: 0, CompileErrors: 0, UnknownErrors: 1, MutationsLeft: 4 } 
2020-04-10 12:02:58,280[INFO]: Current progress: { Survived: 0, Killed: 0, CompileErrors: 0, UnknownErrors: 2, MutationsLeft: 3 } 
2020-04-10 12:02:58,280[INFO]: Running mutation: "Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(10:13))" 
2020-04-10 12:02:58,298[INFO]: Running mutation: "Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(11:13))" 
2020-04-10 12:02:58,317[WARN]: Unexpected exception when running Proj: ClassLibrary1, File: Class1.cs(Hello(M) - @(22:13)) 
2020-04-10 12:02:58,329[INFO]: Compiling mutation Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(10:13)) to c:\users\user\appdata\local\microsoft\visualstudio\16.0_ffb9c984\extensions\yb2lymwz.gkl\TestRun\1myrp42w.jw4\ClassLibrary1.dll 
2020-04-10 12:02:58,330[INFO]: Compiling mutation Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(11:13)) to c:\users\user\appdata\local\microsoft\visualstudio\16.0_ffb9c984\extensions\yb2lymwz.gkl\TestRun\s3bqha4z.1jg\ClassLibrary1.dll 
2020-04-10 12:02:58,330[INFO]: Will put it in the unknown category. 
2020-04-10 12:02:58,334[INFO]: Current progress: { Survived: 0, Killed: 0, CompileErrors: 0, UnknownErrors: 3, MutationsLeft: 2 } 
2020-04-10 12:02:58,335[INFO]: Compiled Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(10:13)) successfully. 
2020-04-10 12:02:58,336[INFO]: Compiled Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(11:13)) successfully. 
2020-04-10 12:02:58,350[INFO]: Starting to run tests in XUnitTestProject1.dll 
2020-04-10 12:02:58,350[INFO]: Starting to run tests in XUnitTestProject1.dll 
2020-04-10 12:03:00,877[WARN]: Unexpected exception when running Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(11:13)) 
2020-04-10 12:03:00,880[INFO]: Will put it in the unknown category. 
2020-04-10 12:03:00,881[INFO]: Current progress: { Survived: 0, Killed: 0, CompileErrors: 0, UnknownErrors: 4, MutationsLeft: 1 } 
2020-04-10 12:03:00,898[WARN]: Unexpected exception when running Proj: ClassLibrary1, File: Class1.cs(Average(C) - @(10:13)) 
2020-04-10 12:03:00,899[INFO]: Will put it in the unknown category. 
2020-04-10 12:03:00,900[INFO]: Current progress: { Survived: 0, Killed: 0, CompileErrors: 0, UnknownErrors: 5, MutationsLeft: 0 } 
2020-04-10 12:03:00,913[INFO]: Your mutation score: 100% 
2020-04-10 12:03:00,915[INFO]: # Handled ExecuteMutationsCommand #

**Comment by paireks** [comment]
Yes, it was the language :D 

Thank you for your help, 5 stars ;)

**Comment by MilleBo** [comment]
Cool! Happy it worked. 

But I should look for some better way to do it then so we support multiple language. And improve the logging so you actually see the error. 

But thanks for reporting it! We fixed the xunit bug at least.
